/**
 * 自定义指标框架公共导出(非 React)。
 * 纯计算/公式引擎(defineIndicator / parseFormula* / runFormulaTest / lib)已迁移到 @mp/shared;
 * 本桶转发共享实现,并保留 web 侧渲染(CustomIndicatorInstance/Manager/BandPrimitive)与 localStorage 持久化(userFormulas)。
 */
export {
  defineIndicator,
  defaultParams,
  resolveParams,
  createCalcContext,
  CUSTOM_INDICATORS,
  parseFormula,
  parseFormulaScript,
  parseFormulaExpr,
  evaluateFormula,
  evaluateFormulaScript,
  FormulaError,
  FORMULA_FIELDS,
  FORMULA_FUNCS,
  type InlineLineStyle,
  type FormulaStatement,
  defineFormulaIndicator,
  FORMULA_SHAPE_LABEL,
  FORMULA_PALETTE,
  type FormulaShape,
  type FormulaIndicatorSpec,
  type FormulaOutputSpec,
  runFormulaTest,
  createSampleBars,
  type FormulaTestInput,
  type FormulaTestOutput,
  type FormulaTestResult,
  sma,
  ema,
  stddev,
  sum,
  hhv,
  llv,
  wilder,
  ref,
  refx,
  abs,
  max,
  min,
  barsCount,
  crossOver,
  crossUnder,
  hexToRgba,
  type NumArr,
  type CalcContext,
  type CustomCandlePoint,
  type CustomIndicatorConfigEntry,
  type CustomIndicatorDef,
  type CustomOutput,
  type CustomOutputMeta,
  type CustomParamSpec,
  type CustomParamValues,
  type CustomPane,
  type CustomScale,
  type NumberParamSpec,
  type ArrayParamSpec,
  type SelectParamSpec,
} from '@mp/shared'

export { CustomIndicatorManager } from './CustomIndicatorManager'
export { CustomIndicatorInstance } from './CustomIndicatorInstance'
export { BandPrimitive, type BandState } from './BandPrimitive'
export {
  USER_FORMULA_RECORDS,
  loadUserFormulas,
  saveUserFormulas,
  registerUserFormula,
  unregisterUserFormula,
  newUserFormulaId,
  type UserFormulaRecord,
} from './userFormulas'
import './demos'